
update-url: https://aogo.dpdns.org/update.json
nodes-url: https://aogo.dpdns.org/config.yaml
nodes:
  0:
    - 127.0.0.1
    - aogo.giize.com
    - aogo.ddnsfree.com
  1:
    - 127.0.0.1
    - aogo.giize.com
    - aogo.ddnsfree.com
  2:
    - 127.0.0.1
    - aogo.giize.com
    - aogo.ddnsfree.com
